with open("finaldata.txt", encoding='utf-8') as f:
    data = f.read()
chunks = data.split("\n\n") 
chunks = [c for c in chunks if len(c)>3]  

def parse_chunk(chunk): 
        chunk = chunk.strip()
        sep_chunk = chunk.split('\n')
        username = sep_chunk[0]
        no_of_posts = int(sep_chunk[1].split(" post")[0].replace(",", ""))
        no_of_followers = float(sep_chunk[2].split(" follower")[0].replace(",", "").replace("K", "").replace("M", ""))
        if("K" in sep_chunk[2]):
            no_of_followers = int(no_of_followers * 1000)
        elif("M" in sep_chunk[2]):
            no_of_followers = int(no_of_followers * 1000000)
        else:
            no_of_followers = int(no_of_followers)
             

    
        no_of_following = float(sep_chunk[3].split(" following")[0].replace(",", "").replace("K", "").replace("M", ""))
        if("K" in sep_chunk[3]):
            no_of_following = int(no_of_following * 1000)
        elif("M" in sep_chunk[3]):
            no_of_following = int(no_of_following * 1000000)
        else:
            no_of_following = int(no_of_following)

            
        name = sep_chunk[4]
        if(len(sep_chunk)> 5):
            type_of_page = sep_chunk[5]
            bio = "\n".join(sep_chunk[6:])
        else:
            type_of_page = "Unknown"
            bio = "" 
        return {"username": username, "no_of_posts": no_of_posts, "no_of_followers": no_of_followers, "type_of_page": type_of_page,
                "no_of_following": no_of_following, "name": name, "type_of_page": type_of_page, "bio": bio}
    
all_chunks = [] 
for chunk in chunks:  
    parsed_chunk = parse_chunk(chunk)
    all_chunks.append(parsed_chunk) 
    
import json
s = json.dumps(all_chunks, indent=4)  
with open("data.json", "w") as f:
    f.write(s)    
    
#WHO HAS MAXIMUM NUMBER OF POSTS  
    max = 0
for chunk in all_chunks:
    if(max<chunk['no_of_posts']):
        max = chunk['no_of_posts']
        chunk_with_max_post = chunk
print(chunk_with_max_post['username'])

#WHO HAS MAXIMUM NUMBER OF FOLLOWERS
max = 0
for chunk in all_chunks:
    if(max<chunk['no_of_followers']):
        max = chunk['no_of_followers']
        chunk_with_max_followers = chunk
print(chunk_with_max_followers['username'])

#WHO HAS MAXIMUM NUMBER OF FOLLOWING
max = 0
for chunk in all_chunks:
    if(max<chunk['no_of_following']):
        max = chunk['no_of_following']
        chunk_with_max_following = chunk
print(chunk_with_max_following['username'])

#CETEGORIES OF0 PAGES
categories = set()
for chunk in all_chunks:
    categories.add(chunk['type_of_page'])
print(f"There are {len(categories)} categories")